name: build-and-test
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      
      - name: setup-go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: check go.mod
        run: |
          go mod tidy
          git diff --exit-code go.mod

      - name: build
        run: go build ./...

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      
      - name: setup-go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      
      - name: run test
        run: go test ./... -race -coverprofile=coverage.txt
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
