name: govulncheck
permissions:
  contents: read
on:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: setup-go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck (fail on findings)
        run: $(go env GOPATH)/bin/govulncheck ./...
